# Generated by Django 4.0.4 on 2022-07-29 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='charge',
            fields=[
                ('idcharge', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('jenischarge', models.CharField(max_length=50)),
                ('hargacharge', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='kamar',
            fields=[
                ('idkamar', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('nokamar', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='pelanggan',
            fields=[
                ('idpelanggan', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=50)),
                ('jeniskelamin', models.CharField(max_length=10)),
                ('tanggallahir', models.DateField()),
                ('nohp', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='penyewaan',
            fields=[
                ('idpenyewaan', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('tanggalsewa', models.DateField()),
                ('hargasewa', models.IntegerField()),
                ('idkamar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.kamar')),
                ('idpelanggan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.pelanggan')),
            ],
        ),
        migrations.CreateModel(
            name='detailcharge',
            fields=[
                ('iddetailcharge', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('jumlahitemcharge', models.IntegerField()),
                ('hargacharge', models.IntegerField()),
                ('idcharge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.charge')),
                ('idpenyewaan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.penyewaan')),
            ],
        ),
    ]
