# Generated by Django 4.0.4 on 2022-08-02 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_penyewaan_idkamar'),
    ]

    operations = [
        migrations.AddField(
            model_name='kamar',
            name='jenis',
            field=models.CharField(default='laki-laki', max_length=15),
        ),
        migrations.AddField(
            model_name='kamar',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
