# Generated by Django 4.0.4 on 2022-08-02 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_kamar_jenis_kamar_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detailcharge',
            name='idpenyewaan',
        ),
        migrations.AddField(
            model_name='detailcharge',
            name='idpelanggan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.pelanggan'),
        ),
    ]
