# Generated by Django 4.0.4 on 2022-08-10 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_detailcharge_idpenyewaan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='penyewaan',
            name='ischeckout',
            field=models.BooleanField(default='False'),
        ),
    ]
