# Generated by Django 4.0.4 on 2022-08-10 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_penyewaan_ischeckout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='penyewaan',
            name='ischeckout',
        ),
    ]
