# Generated by Django 4.0.4 on 2022-08-11 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_penyewaan_ischeckout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='penyewaan',
            name='idkamar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.kamar'),
        ),
    ]
